from tasks.easy_task import get_easy_task
from tasks.medium_task import get_medium_task, update_target_positions as medium_update_positions
from tasks.hard_task import get_hard_task, apply_sensor_failures, update_target_positions as hard_update_positions
from tasks.grader import grade_episode